version: "3"

services:
  # Database
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "$MYSQLDB_DOCKER_PORT:$MYSQLDB_DOCKER_PORT"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    networks:
      - mysql-phpmyadmin
  #Aplicação
  app:
    depends_on:
      - db
    build: .
    restart: on-failure
    env_file: .env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.mail.username" : "$EMAIL",
        "spring.mail.password" : "$PASSWORD_EMAIL"
      }'
    networks:
      - mysql-phpmyadmin
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db_data: